### ISSUE TITLE
Next.js Performance Checklist

### ISSUE THREAD

**Issue by sohamsshah** [sohamsshah/pixelsHash#17]
Update the app to improve performance at various areas.

Checklist:
- [X] Images should have height and width attribute
- [X] Properly Sized Images
- [X] Serve static assets with an efficient cache policy
- [X] Accessible Names for Buttons
- [X] <title> for Document
- [ ] Form Elements accessible Labels (cannot be improved as it depends on `react-select`)
- [X] Links should have discernible name
- [X] Add Heading, Skip Link or Landmark region to page
- [X] Lang Attribute for html element
- [X] Document Meta Description
- [X] Valid Robot.txt
- [X] Defer Off-screen Images

Based on Lighthouse Report.
Also Checkout: https://dev.to/endymion1818/nextjs-performance-checklist-5gjb
